# Generated by Django 5.1.1 on 2024-09-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
